// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFriend = "friends"

// Friend mapped from table <friends>
type Friend struct {
	UserID    []byte    `gorm:"column:user_id;type:binary(16);primaryKey;comment:User UUID" json:"user_id"`                                                                           // User UUID
	FriendID  []byte    `gorm:"column:friend_id;type:binary(16);primaryKey;index:fk_friend_id,priority:1;comment:Friend UUID, the user who is a friend of the user" json:"friend_id"` // Friend UUID, the user who is a friend of the user
	Remark    string    `gorm:"column:remark;type:text;comment:A remark or note about the friendship (optional)" json:"remark"`                                                       // A remark or note about the friendship (optional)
	Deleted   int32     `gorm:"column:deleted;type:tinyint;not null;comment:Indicates whether the friendship is deleted (0: active, 1: deleted)" json:"deleted"`                      // Indicates whether the friendship is deleted (0: active, 1: deleted)
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:Friendship creation time" json:"created_at"`                                        // Friendship creation time
}

// TableName Friend's table name
func (*Friend) TableName() string {
	return TableNameFriend
}
