// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFriendRequest = "friend_requests"

// FriendRequest mapped from table <friend_requests>
type FriendRequest struct {
	RequestID          []byte    `gorm:"column:request_id;type:binary(16);primaryKey;comment:UUID for the friend request" json:"request_id"`                                                                                   // UUID for the friend request
	UserID             []byte    `gorm:"column:user_id;type:binary(16);not null;uniqueIndex:unique_user_friend,priority:1;comment:User UUID sending the request" json:"user_id"`                                               // User UUID sending the request
	FriendID           []byte    `gorm:"column:friend_id;type:binary(16);not null;uniqueIndex:unique_user_friend,priority:2;index:fk_request_friend_id,priority:1;comment:Friend UUID receiving the request" json:"friend_id"` // Friend UUID receiving the request
	RequestMessage     string    `gorm:"column:request_message;type:text;comment:Message sent with the friend request (optional)" json:"request_message"`                                                                      // Message sent with the friend request (optional)
	VerificationStatus int32     `gorm:"column:verification_status;type:tinyint;not null;comment:0: pending, 1: accepted, 2: rejected" json:"verification_status"`                                                             // 0: pending, 1: accepted, 2: rejected
	CreatedAt          time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:Request creation time" json:"created_at"`                                                                           // Request creation time
	ExpirationAt       time.Time `gorm:"column:expiration_at;type:timestamp;default:(now() + interval 3 day);comment:Time when the request expires" json:"expiration_at"`                                                      // Time when the request expires
}

// TableName FriendRequest's table name
func (*FriendRequest) TableName() string {
	return TableNameFriendRequest
}
