// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID    []byte    `gorm:"column:user_id;type:binary(16);primaryKey;comment:UUID generated" json:"user_id"` // UUID generated
	Username  string    `gorm:"column:username;type:varchar(255);not null" json:"username"`
	Password  string    `gorm:"column:password;type:varchar(255);not null;comment:Hashed password" json:"password"` // Hashed password
	Email     string    `gorm:"column:email;type:varchar(255);not null;uniqueIndex:idx_unique_email,priority:1" json:"email"`
	Phone     string    `gorm:"column:phone;type:varchar(15);not null;uniqueIndex:idx_unique_phone,priority:1" json:"phone"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:created time" json:"created_at"` // created time
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:updated time" json:"updated_at"` // updated time
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
