// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserProfile = "user_profiles"

// UserProfile mapped from table <user_profiles>
type UserProfile struct {
	UserID       []byte    `gorm:"column:user_id;type:binary(16);primaryKey;comment:User UUID (foreign key to users table)" json:"user_id"` // User UUID (foreign key to users table)
	AvatarURL    string    `gorm:"column:avatar_url;type:text;not null" json:"avatar_url"`
	OnlineStatus int32     `gorm:"column:online_status;type:tinyint;not null;comment:0: offline, 1: online" json:"online_status"`                // 0: offline, 1: online
	Bio          string    `gorm:"column:bio;type:text;comment:Short biography or status message" json:"bio"`                                    // Short biography or status message
	Birthday     time.Time `gorm:"column:birthday;type:date;comment:Users date of birth" json:"birthday"`                                        // Users date of birth
	Gender       string    `gorm:"column:gender;type:enum('unspecified','male','female');default:unspecified;comment:User gender" json:"gender"` // User gender
	Location     string    `gorm:"column:location;type:varchar(255);comment:Users location or timezone" json:"location"`                         // Users location or timezone
	LastSeenAt   time.Time `gorm:"column:last_seen_at;type:timestamp;comment:Last seen timestamp for the user" json:"last_seen_at"`              // Last seen timestamp for the user
}

// TableName UserProfile's table name
func (*UserProfile) TableName() string {
	return TableNameUserProfile
}
